### ISSUE TITLE
server error on trnsprt.ch

### ISSUE THREAD

**Issue by Remo** [fabian/trnsprt.ch#9]
When I try to open http://trnsprt.ch/to/Z%C3%BCrich%20HB/from/luzern/at/2015-11-12%2016:00 I get `Whoops, looks like something went wrong.`. I assume you've got something in your log file.

**Comment by Remo** [comment]
works again...

**Comment by fabian** [comment]
Yes unfortunately sometimes the connection of transport.opendata.ch to SBB fails.

Hmm, maybe I could retry the  request in those cases…

**Comment by Remo** [comment]
I think a message like: "Connection to opendata.ch has failed, please try again later" would be sufficient.
